[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
derisk-type = { path = "../derisk-type" }
risc0-zkvm = { version = "^3.0.3", features = ["prove"] }
risc0-groth16 = "3.0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
alloy = { version = "0.6", features = ["full"] }
eyre = "0.6"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15"
bincode = "1.3"
