[package]
name = "aave-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = [
    'std',
] }
derisk-type = { path = "../../../derisk-type" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
